AWSTemplateFormatVersion: "2010-09-09"
Transform: [AWS::LanguageExtensions, AWS::Serverless-2016-10-31]
Description: "Digital Identity IPV CRI Ipv-Cri-Check-Hmrc-Smoke-Tests API"
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [ dev, localdev, build, staging, integration, production ]
    ConstraintDescription: must be dev, localdev, build, staging, integration or production
  CodeSigningConfigArn:
    Type: String
    Default: ""

Conditions:
  EnforceCodeSigning: !Not [!Equals [!Ref CodeSigningConfigArn, ""]]
  IsDevEnvironment: !Equals [!Ref Environment, dev]
  IsLocalDevEnvironment: !Equals [!Ref Environment, localdev]
  IsDevLikeEnvironment:
    !Or [!Condition IsLocalDevEnvironment, !Condition IsDevEnvironment]

Globals:
  Function:
    Timeout: 30
    CodeUri: ..
    Runtime: nodejs18.x
    Architectures: [arm64]

Resources:
  CanaryInvokerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Sourcemap: true
    Properties:
      Timeout: 60
      Handler: lambdas/canary-invoker/src/canary-invoker-handler.lambdaHandler
      LoggingConfig:
        LogGroup: !Sub /aws/lambda/${AWS::StackName}/CanaryInvokerFunction
      CodeSigningConfigArn:
        !If [EnforceCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue]
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - synthetics:StartCanary
              - synthetics:GetCanaryRuns
            Resource: !Sub arn:aws:synthetics:${AWS::Region}:${AWS::AccountId}:canary:*

  CanaryInvokerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AWS::StackName}/CanaryInvokerFunction
      RetentionInDays: !If [ IsDevLikeEnvironment, 7, 30 ]

Outputs:
  CanaryInvokerFunction:
    Description: CanaryInvoker Lambda Function Name
    Value: !Ref CanaryInvokerFunction
  CanaryInvokerFunctionArn:
    Description: CanaryInvoker Lambda Function ARN
    Value: !GetAtt CanaryInvokerFunction.Arn
  CanaryInvokerFunctionIamRoleArn:
    Description: Implicit IAM Role created for CanaryInvoker function
    Value: !GetAtt CanaryInvokerFunctionRole.Arn
