AWSTemplateFormatVersion: "2010-09-09"
Transform: [AWS::LanguageExtensions, AWS::Serverless-2016-10-31]
Description: "Digital Identity IPV CRI Ipv-Cri-Check-Hmrc-Smoke-Tests API"
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [ dev, localdev, build, staging, integration, production ]
    ConstraintDescription: must be dev, localdev, build, staging, integration or production
  CodeSigningConfigArn:
    Type: String
    Default: ""
  PermissionsBoundary:
    Type: String
    Default: ""

Conditions:
  EnforceCodeSigning: !Not [!Equals [!Ref CodeSigningConfigArn, ""]]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, ""]]
  IsDevEnvironment: !Equals [!Ref Environment, dev]
  IsLocalDevEnvironment: !Equals [!Ref Environment, localdev]
  IsDevLikeEnvironment:
    !Or [!Condition IsLocalDevEnvironment, !Condition IsDevEnvironment]

Globals:
  Function:
    Timeout: 30
    CodeUri: ..
    Runtime: nodejs18.x
    Architectures: [arm64]
    PermissionsBoundary:
      !If [UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]
    VpcConfig:
      SecurityGroupIds:
        - !ImportValue cri-vpc-AWSServicesEndpointSecurityGroupId
      SubnetIds:
        - !ImportValue cri-vpc-ProtectedSubnetIdA
        - !ImportValue cri-vpc-ProtectedSubnetIdB
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps

Resources:
  CanaryInvokerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Sourcemap: true
    Properties:
      Handler: lambdas/canary-invoker/src/canary-invoker-handler.lambdaHandler
      LoggingConfig:
        LogGroup: !Sub /aws/lambda/${AWS::StackName}/CanaryInvokerFunction
      CodeSigningConfigArn:
        !If [EnforceCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue]

  CanaryInvokerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AWS::StackName}/CanaryInvokerFunction
      RetentionInDays: !If [ IsDevLikeEnvironment, 7, 30 ]

Outputs:
  CanaryInvokerFunctionArn:
    Description: CanaryInvoker Lambda Function ARN
    Value: !GetAtt CanaryInvokerFunction.Arn
  CanaryInvokerFunctionIamRoleArn:
    Description: Implicit IAM Role created for CanaryInvoker function
    Value: !GetAtt CanaryInvokerFunctionRole.Arn
