AWSTemplateFormatVersion: "2010-09-09"
Transform: [ AWS::LanguageExtensions, AWS::Serverless-2016-10-31 ]
Description: "Digital Identity IPV CRI Ipv-Cri-Check-Hmrc-Smoke-Tests API"

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [ dev, localdev, build, staging, integration, production ]
    ConstraintDescription: must be dev, localdev, build, staging, integration or production
  CodeSigningConfigArn:
    Type: String
    Default: ""
  PermissionsBoundary:
    Type: String
    Default: ""

Conditions:
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, ""]]
  EnforceCodeSigning: !Not [ !Equals [ !Ref CodeSigningConfigArn, "" ] ]
  IsDevEnvironment: !Equals [ !Ref Environment, dev ]
  IsLocalDevEnvironment: !Equals [ !Ref Environment, localdev ]
  IsDevLikeEnvironment:
    !Or [ !Condition IsLocalDevEnvironment, !Condition IsDevEnvironment ]
  IsNotDevEnvironment: !Not
    - !Condition IsDevLikeEnvironment
  IsProdEnvironment: !Equals [ !Ref Environment, production ]

Globals:
  Function:
    Timeout: 30
    CodeUri: ..
    Runtime: nodejs18.x
    Architectures: [ arm64 ]
    PermissionsBoundary:
      !If [ UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue ]

Mappings:
  CriButtonOnCoreStub:
    Environment:
      dev: 3
      build: 5
      staging: 8

Resources:

  NinoHappyCanariesAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsNotDevEnvironment
    Properties:
      AlarmDescription: "Alarm for when Nino Canaries Fail"
      AlarmName: "nino-happy-canaries-failure"
      ActionsEnabled: true
      Namespace: "CloudWatchSynthetics"
      MetricName: "Failed"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Statistic: Sum
      Period: 3600
      Threshold: 3
      TreatMissingData: notBreaching
      AlarmActions:
        - !ImportValue platform-alarm-warning-alert-topic
      Dimensions:
        - Name: "CanaryName"
          Value: !Ref NinoHappyCanaries

  NinoCICanariesAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsNotDevEnvironment
    Properties:
      AlarmDescription: "Alarm for when Nino Canaries Fail"
      AlarmName: "nino-ci-canaries-failure"
      ActionsEnabled: true
      Namespace: "CloudWatchSynthetics"
      MetricName: "Failed"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Statistic: Sum
      Period: 3600
      Threshold: 3
      TreatMissingData: notBreaching
      AlarmActions:
        - !ImportValue platform-alarm-warning-alert-topic
      Dimensions:
        - Name: "CanaryName"
          Value: !Ref NinoCICanaries

  CanariesRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary:
        !If [ UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue ]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - synthetics.amazonaws.com
                - lambda.amazonaws.com
      Policies:
        - PolicyName: NinoCanariesExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - s3:PutObject
                  - s3:GetBucketLocation
                  - s3:ListAllMyBuckets
                  - cloudwatch:PutMetricData
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents

  CanariesBucket:
    Type: AWS::S3::Bucket

  CanaryInvokerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Sourcemap: true
    Properties:
      Timeout: 60
      Handler: lambdas/canary-invoker/src/canary-invoker-handler.lambdaHandler
      LoggingConfig:
        LogGroup: !Sub /aws/lambda/${AWS::StackName}/CanaryInvokerFunction
      CodeSigningConfigArn:
        !If [ EnforceCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue ]
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - synthetics:StartCanary
              - synthetics:GetCanaryRuns
            Resource: !Sub arn:aws:synthetics:${AWS::Region}:${AWS::AccountId}:canary:*

  CanaryInvokerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AWS::StackName}/CanaryInvokerFunction
      RetentionInDays: !If [ IsProdEnvironment, 30, 7 ]

  NinoCICanaries:
    Type: AWS::Synthetics::Canary
    Properties:
      Name: !Sub ${AWS::StackName}-ci
      StartCanaryAfterCreation: true
      ArtifactS3Location: !Sub s3://${CanariesBucket}/ci
      ExecutionRoleArn: !GetAtt CanariesRole.Arn
      RuntimeVersion: syn-nodejs-puppeteer-7.0
      Schedule:
        Expression: rate(15 minutes)
      Tags:
        - Key: blueprint
          Value: canaryRecorder
        - Key: code location
          Value: ipv-cri-check-hmrc-smoke-tests
      Code:
        Handler: exports.handler
        Script:
          !Sub
          - |
            var synthetics = require('Synthetics');
            const log = require('SyntheticsLogger');
            const escapeXpathString = (str) => {
              return str.replace(/'/g, `', "'", '`);
            };
            const clickByText = async (page, text) => {
              const escapedText = escapeXpathString(text);
              const linkHandlers = await page.$x("//a[contains(text(), '" + escapedText + "')]");
              if (linkHandlers.length > 0) {
                await linkHandlers[0].click();
              } else {
                throw new Error('Link not found:' + text);
              }
            };
            const recordedScript = async function () {
              let page = await synthetics.getPage();
              const navigationPromise = page.waitForNavigation()
              await synthetics.executeStep('Goto Stubs Page', async function() {
                await page.goto("${CoreStubUrl}", { waitUntil: 'domcontentloaded', timeout: 60000 })
              })
              await page.setViewport({ width: 1364, height: 695 })
              await synthetics.executeStep('Click Check HMRC Build Evidence Requested', async function() {
                await page.waitForSelector('.govuk-template__body > .govuk-width-container > #main-content > a:nth-child(${CoreStubButton}) > .govuk-button')
                await page.click('.govuk-template__body > .govuk-width-container > #main-content > a:nth-child(${CoreStubButton}) > .govuk-button')
              })
              await navigationPromise
              await synthetics.executeStep('Click Continue on Evidence Requested page', async function() {
                await page.waitForSelector('form > .govuk-form-group > .govuk-fieldset > .govuk-button-group > .govuk-button')
                await page.click('form > .govuk-form-group > .govuk-fieldset > .govuk-button-group > .govuk-button')
              })
              await navigationPromise
              await synthetics.executeStep("Click New User Hyperlink", async function () {
                await clickByText(page, "New User");
              });
              await navigationPromise
              await synthetics.executeStep('Click Firstname Box', async function() {
                await page.waitForSelector('.govuk-width-container > #main-content #firstName')
                await page.click('.govuk-width-container > #main-content #firstName')
              })
              await synthetics.executeStep('Enter Firstname', async function() {
                await page.type('.govuk-width-container > #main-content #firstName', "Error")
              })
              await synthetics.executeStep('Click Surname Box', async function() {
                await page.waitForSelector('.govuk-width-container > #main-content #surname')
                await page.click('.govuk-width-container > #main-content #surname')
              })
              await synthetics.executeStep('Enter Surname', async function() {
                await page.type('.govuk-width-container > #main-content #surname', "NoCidForNino")
              })
              await synthetics.executeStep('Click Go', async function() {
                await page.waitForSelector('.govuk-template__body > .govuk-width-container > #main-content > form > .govuk-button')
                await page.click('.govuk-template__body > .govuk-width-container > #main-content > form > .govuk-button')
              })
              await navigationPromise
              await synthetics.executeStep('Click NI Box', async function() {
                await page.waitForSelector('.govuk-grid-row #nationalInsuranceNumber')
                await page.click('.govuk-grid-row #nationalInsuranceNumber')
              })
              await synthetics.executeStep('Enter NINO', async function() {
                await page.type('.govuk-grid-row #nationalInsuranceNumber', "AA123456C")
              })
              await synthetics.executeStep('Click Continue', async function() {
                await page.waitForSelector('#main-content #continue')
                await page.click('#main-content #continue')
              })
              await navigationPromise
              await synthetics.executeStep('Click Retry Button', async function() {
                await page.waitForSelector('.govuk-form-group > #retryNationalInsuranceRadio-fieldset #retryNationalInsuranceRadio')
                await page.click('.govuk-form-group > #retryNationalInsuranceRadio-fieldset #retryNationalInsuranceRadio')
              })
              await synthetics.executeStep('Enter Retry NINO', async function() {
                await page.type('.govuk-form-group > #retryNationalInsuranceRadio-fieldset #retryNationalInsuranceRadio', "retryNationalInsurance")
              })
              await synthetics.executeStep('Click Continue', async function() {
                await page.waitForSelector('#main-content #continue')
                await page.click('#main-content #continue')
              })
              await navigationPromise
              await synthetics.executeStep('Click Continue', async function() {
                await page.waitForSelector('#main-content #continue')
                await page.click('#main-content #continue')
              })
              await navigationPromise
              await synthetics.executeStep('VerifyVerifiableCredentials', async function() {
                const spanSelector = '.govuk-details__summary-text';
                await page.waitForSelector(spanSelector, { timeout: 60000 });
                const headingSelector = '.govuk-heading-l';
                await page.waitForSelector(headingSelector, { timeout: 60000 });
              })
              await synthetics.executeStep('Get VC And Assert CI', async function() {
                const data = await page.evaluate(() => {
                  const element = document.querySelector("[id='data']");
                  return element.textContent.trim();
                });
                log.info('Extracted data:', data);
                const json = JSON.parse(data);
                if (!json.vc.evidence[0].ci) {
                  throw new Error("Assertion failed: 'CI' is not present in the data");
                }
              })
            };
            exports.handler = async () => {
              return await recordedScript();
            };
          - CoreStubUrl: !Sub "{{resolve:ssm:/check-hmrc-cri-api/smoke-tests/core-stub-url}}"
            CoreStubButton: !FindInMap [CriButtonOnCoreStub, "Environment", !Ref Environment]

  NinoHappyCanaries:
    Type: AWS::Synthetics::Canary
    Properties:
      Name: !Sub ${AWS::StackName}-happy
      StartCanaryAfterCreation: true
      ArtifactS3Location: !Sub s3://${CanariesBucket}/happy
      ExecutionRoleArn: !GetAtt CanariesRole.Arn
      RuntimeVersion: syn-nodejs-puppeteer-7.0
      Schedule:
        Expression: rate(15 minutes)
      Tags:
        - Key: blueprint
          Value: canaryRecorder
        - Key: code location
          Value: ipv-cri-check-hmrc-smoke-tests
      Code:
        Handler: exports.handler
        Script:
          !Sub
          - |
            var synthetics = require('Synthetics');
            const log = require('SyntheticsLogger');
            const escapeXpathString = (str) => {
              return str.replace(/'/g, `', "'", '`);
            };
            const clickByText = async (page, text) => {
              const escapedText = escapeXpathString(text);
              const linkHandlers = await page.$x("//a[contains(text(), '" + escapedText + "')]");
              if (linkHandlers.length > 0) {
                await linkHandlers[0].click();
              } else {
                throw new Error('Link not found:' + text);
              }
            };
            const recordedScript = async function () {
              let page = await synthetics.getPage();
              const navigationPromise = page.waitForNavigation()
              await synthetics.executeStep('Goto Stubs Page', async function() {
                const url = '${CoreStubUrl}';
                await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 })
              })
              await page.setViewport({ width: 1364, height: 695 })
              await synthetics.executeStep('Click Check HMRC Build Evidence Requested', async function() {
                await page.waitForSelector('.govuk-template__body > .govuk-width-container > #main-content > a:nth-child(${CoreStubButton}) > .govuk-button')
                await page.click('.govuk-template__body > .govuk-width-container > #main-content > a:nth-child(${CoreStubButton}) > .govuk-button')
              })
              await navigationPromise
              await synthetics.executeStep('Click Continue on Evidence Requested page', async function() {
                await page.waitForSelector('form > .govuk-form-group > .govuk-fieldset > .govuk-button-group > .govuk-button')
                await page.click('form > .govuk-form-group > .govuk-fieldset > .govuk-button-group > .govuk-button')
              })
              await navigationPromise
              await synthetics.executeStep("Click New User Hyperlink", async function () {
                await clickByText(page, "New User");
              });
              await navigationPromise
              await synthetics.executeStep('Click Firstname Box', async function() {
                await page.waitForSelector('.govuk-width-container > #main-content #firstName')
                await page.click('.govuk-width-container > #main-content #firstName')
              })
              await synthetics.executeStep('Enter Firstname', async function() {
                await page.type('.govuk-width-container > #main-content #firstName', "Jim")
              })
              await synthetics.executeStep('Click Surname Box', async function() {
                await page.waitForSelector('.govuk-width-container > #main-content #surname')
                await page.click('.govuk-width-container > #main-content #surname')
              })
              await synthetics.executeStep('Enter Surname', async function() {
                await page.type('.govuk-width-container > #main-content #surname', "Ferguson")
              })
              await synthetics.executeStep('Click Go', async function() {
                await page.waitForSelector('.govuk-template__body > .govuk-width-container > #main-content > form > .govuk-button')
                await page.click('.govuk-template__body > .govuk-width-container > #main-content > form > .govuk-button')
              })
              await navigationPromise
              await synthetics.executeStep('Click NI Box', async function() {
                await page.waitForSelector('.govuk-grid-row #nationalInsuranceNumber')
                await page.click('.govuk-grid-row #nationalInsuranceNumber')
              })
              await synthetics.executeStep('Enter NINO', async function() {
                await page.type('.govuk-grid-row #nationalInsuranceNumber', "AA123456C")
              })
              await synthetics.executeStep('Click Continue', async function() {
                await page.waitForSelector('#main-content #continue')
                await page.click('#main-content #continue')
              })
              await navigationPromise
              await synthetics.executeStep('VerifyVerifiableCredentials', async function() {
                const spanSelector = '.govuk-details__summary-text';
                await page.waitForSelector(spanSelector, { timeout: 60000 });
                const headingSelector = '.govuk-heading-l';
                await page.waitForSelector(headingSelector, { timeout: 60000 });
              })
              await synthetics.executeStep('Get VC And Assert CI', async function() {
                const data = await page.evaluate(() => {
                  const element = document.querySelector("[id='data']");
                  return element.textContent.trim();
                });
                log.info('Extracted data:', data);
                const json = JSON.parse(data);
                if (json.vc.evidence[0].ci) {
                  throw new Error("Assertion failed: CI is present in the data");
                }
              })
            };
            exports.handler = async () => {
              return await recordedScript();
            };
          - CoreStubUrl: !Sub "{{resolve:ssm:/check-hmrc-cri-api/smoke-tests/core-stub-url}}"
            CoreStubButton: !FindInMap [CriButtonOnCoreStub, "Environment", !Ref Environment]

Outputs:
  CanaryInvokerFunction:
    Description: CanaryInvoker Lambda Function Name
    Value: !Ref CanaryInvokerFunction
  CanaryInvokerFunctionArn:
    Description: CanaryInvoker Lambda Function ARN
    Value: !GetAtt CanaryInvokerFunction.Arn
  CanaryInvokerFunctionIamRoleArn:
    Description: Implicit IAM Role created for CanaryInvoker function
    Value: !GetAtt CanaryInvokerFunctionRole.Arn
