AWSTemplateFormatVersion: "2010-09-09"
Transform: [AWS::LanguageExtensions, AWS::Serverless-2016-10-31]
Description: Digital Identity IPV CRI Ipv-Cri-Check-Hmrc-Smoke-Tests API

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, localdev, build, staging, integration, production]
    ConstraintDescription: Must be dev, localdev, build, staging, integration or production
  CodeSigningConfigArn:
    Type: String
    Default: ""
  PermissionsBoundary:
    Type: String
    Default: ""

Conditions:
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, ""]]
  EnforceCodeSigning: !Not [!Equals [!Ref CodeSigningConfigArn, ""]]

Globals:
  Function:
    Timeout: 30
    CodeUri: ..
    Runtime: nodejs22.x
    Architectures: [arm64]
    PermissionsBoundary: !If [UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps

Mappings:
  CriButtonOnCoreStub:
    Environment:
      dev: 3
      build: 5
      staging: 7

Resources:
  CanariesRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary:
        !If [UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: NinoCanariesExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !GetAtt CanariesBucket.Arn
                Action: s3:GetBucketLocation
              - Effect: Allow
                Resource: !Sub ${CanariesBucket.Arn}/*
                Action: s3:PutObject
              - Effect: Allow
                Resource: "*"
                Action:
                  - s3:ListAllMyBuckets
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - cloudwatch:PutMetricData

  CanariesBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ExampleParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/sk-test
      Type: String
      Value:
        Fn::ToJsonString:
          "CoreStubUrl": !Sub "{{resolve:ssm:/check-hmrc-cri-api/smoke-tests/core-stub-url}}"
          "CoreStubButton": !FindInMap [ CriButtonOnCoreStub, "Environment", !Ref Environment ]

  CanaryRunnerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Sourcemap: true
    Properties:
      Timeout: 60
      Handler: lambdas/canary-runner/src/canary-runner-handler.lambdaHandler
      FunctionName: !Select [3, !Split ["/", !Ref CanaryRunnerFunctionLogGroup]]
      CodeSigningConfigArn: !If [EnforceCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue]
      LoggingConfig:
        LogGroup: !Ref CanaryRunnerFunctionLogGroup
      Policies:
        - Statement:
            Sid: AllowRunCanaries
            Effect: Allow
            Action:
              - synthetics:GetCanary
              - synthetics:StopCanary
              - synthetics:StartCanary
              - synthetics:DescribeCanariesLastRun
            Resource:
              - !Sub arn:aws:synthetics:${AWS::Region}:${AWS::AccountId}:canary:${NinoCICanary}

  CanaryRunnerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AWS::StackName}-CanaryRunnerFunction
      RetentionInDays: 30

  NinoCICanary:
    Type: AWS::Synthetics::Canary
    Properties:
      Name: sk-test-ci
      StartCanaryAfterCreation: true
      ArtifactS3Location: !Sub s3://${CanariesBucket}/ci
      ExecutionRoleArn: !GetAtt CanariesRole.Arn
      RuntimeVersion: syn-nodejs-puppeteer-7.0
      Schedule:
        Expression: rate(15 minutes)
      Tags:
        - Key: Blueprint
          Value: canaryRecorder
        - Key: Repository
          Value: govuk-one-login/ipv-cri-check-hmrc-smoke-tests
      Code:
        S3Bucket: synthetic-canaries-bucket
        S3Key: canaries.zip
        Handler: nino-ci-canary.handler
      RunConfig:
        ActiveTracing: True
        EnvironmentVariables:
            CoreStubUrl: !Sub "{{resolve:ssm:/check-hmrc-cri-api/smoke-tests/core-stub-url}}"
            CoreStubButton: !FindInMap [CriButtonOnCoreStub, "Environment", !Ref Environment]

Outputs:
  CanaryNames:
    Description: The names of the all canaries created by the stack
    Value: !Join
      - ","
      - - !Ref NinoCICanary
