name: Scan repository

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    # Every Monday at 9am
    - cron: "0 9 * * 1"

concurrency:
  group: scan-repo-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  # TODO: Enable sonarcloud without coverage in shared actions
  #sonarcloud:
  #  name: SonarCloud
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Run SonarCloud scan
  #      uses: govuk-one-login/github-actions/code-quality/sonarcloud@3b8133beab89c813cf15375904be82bf9ab79a91
  #      with:
  #        sonar-token: ${{ secrets.SONAR_TOKEN }}
  #        github-token: ${{ secrets.GITHUB_TOKEN }}

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Run CodeQL scan
        uses: govuk-one-login/github-actions/code-quality/codeql@3b8133beab89c813cf15375904be82bf9ab79a91
        with:
          languages: javascript-typescript
